spring.application.name=agrosphere

# =========================================
# ORACLE DATABASE
# =========================================

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm566063
spring.datasource.password=070906
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# =========================================
# SWAGGER
# =========================================

springdoc.swagger-ui.path=/swagger

# =========================================
# SERVER
# =========================================

server.port=8080